name: Release
on:
    workflow_dispatch:
        inputs:
            version_type:
                description: 'Version type'
                required: true
                default: release
                type: choice
                options:
                    - release
                    - beta
                    - alpha

jobs:
    build:
        strategy:
            matrix:
                java: [ 17 ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: setup JDK${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}

            -   uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/loom-cache
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
                    restore-keys: ${{ runner.os }}-gradle

            -   name: Get Mod ID
                id: mod_id
                run: grep "archives_base_name" gradle.properties | sed "s/\s//g" >> $GITHUB_OUTPUT

            -   name: Get Mod Version
                id: mod_version
                run: grep "version" gradle.properties | sed "s/\s//g" >> $GITHUB_OUTPUT

            -   name: Get Platform Version
                id: platform_version
                run: grep "minecraft" gradle/libs.versions.toml | head -n 1 | sed "s/\s//g" | tr -d \" >> $GITHUB_OUTPUT

            -   name: Get Composite Version
                id: composite_version
                run: echo "composite_version=${{ steps.mod_version.outputs.version }}+${{ steps.platform_version.outputs.minecraft }}" >> $GITHUB_OUTPUT

            -   name: Publish
                env:
                    MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
                    mint_version_type: ${{ inputs.version_type }}
                run: ./gradlew build modrinth

            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ steps.composite_version.outputs.composite_version }}
                    release_name: Mint ${{ steps.composite_version.outputs.composite_version }}
                    body_path: CHANGELOG.md
                    draft: false
                    prerelease: ${{ inputs.version_type != 'release' }}

            -   name: Upload Release Asset
                id: upload_release_asset
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: ./build/libs/${{ steps.mod_id.outputs.archives_base_name }}-${{ steps.composite_version.outputs.composite_version }}.jar
                    asset_name: ${{ steps.mod_id.outputs.archives_base_name }}-${{ steps.composite_version.outputs.composite_version }}.jar
                    asset_content_type: application/java-archive